version: "3"
services:
  api:
    container_name: api
    build: .
    image: unu_api
    ports:
      - 8000:80
    volumes:
      - ./app:/app
    depends_on:
      - redis
    env_file: ./app/.env
    restart: on-failure

  worker:
    container_name: worker
    image: unu_api
    command: python3 worker/main.py
    volumes:
      - ./app:/app
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
