version: "3"
services:
  api:
    container_name: unu_api
    build: .
    image: unu_api
    ports:
      - 8000:80
    volumes:
      - ./app:/app
    env_file: ./app/.env
    command: bash -c "coverage run -m pytest && coverage report"
