version: "3"
services:
  # API serices
  api:
    container_name: api
    image: unu_api
    ports:
      - 8000:80
    env_file: ./app/.env
    volumes:
      - ./app:/app
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    depends_on:
      - redis
    restart: on-failure
  # Wroker services
  worker:
    container_name: worker
    image: unu_api
    command: python3 worker/main.py
    volumes:
      - ./app:/app
    depends_on:
      - redis
  # Redis services
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
