version: "3"
services:
  api:
    container_name: api
    image: unu_api
    ports:
      - 8000:80
    env_file: ./app/.env
    volumes:
      - ./app:/app
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    depends_on:
      - redis
      - db
    restart: on-failure
    command: "/start-reload.sh"

  db:
    container_name: unu_db
    image: postgres:13
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./app/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

  worker:
    container_name: worker
    image: unu_api
    command: python3 worker/main.py
    volumes:
      - ./app:/app
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always

  # dashboard:
  #   build: ./app/worker
  #   image: dashboard
  #   container_name: dashboard
  #   ports:
  #     - 9181:9181
  #   command: rq-dashboard -H redis
  #   depends_on:
  #     - redis
  #     - worker

volumes:
  app-db-data:
